spring:
  application:
    name: iot-service
  datasource:
    url: jdbc:sqlserver://athari-flowbox.database.windows.net:1433;database=athari_iot;user=athari-dev-user@athari-flowbox;password=Vuitton4032;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    url: jdbc:postgresql://localhost:5432/athari_flowbox_iot
    password: password
    username: samtoya
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
server:
  port: 34200
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}